# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Chengzhi Song
tagline:          'Truzz!'
description:      'Life is like a box of Chocolate!<br>Welcome to my personal blog<br>Sharing life and tech.'
url:              https://chengzhisong6.github.io/
# baseurl:          /scz.github.io/

author:
  name:           'Chengzhi Song'
  email:          songchenghziinhk@gmail.com

paginate:         5
paginate_path: "blog/page:num"

gems: [jekyll-paginate]

# custom vars
since:                  2015
# google_analytics:       UA-63207330-1
emailme:                mailto:songchenghziinhk@gmail.com
github:
  repo:                 https://github.com/ChengzhiSONG6/ChengzhiSONG6.github.io
version:                Apr.29.2020
# orcid_username:         0000-0003-4281-5120
# researcherid_username:  R-3094-2018
googlescholar_username: S6_hs6wAAAAJ&hl
# researchgate_username:  
linkedin_username:      ChengzhiSong
github_username:        ChengzhiSong6
youtube_username: UC8cGoer178dqIYzl2TPtYQA
share_pdf:              yes
share_video:            no
# facebook_username: zrwang.cuhk
# google_plus_username: 115306810481973645007
# twitter_username: wangzerui
# instagram_username: wzr.mavericker
# cv_chn: yes
