# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Chengzhi Song
# tagline:          'Life is like a box of Chocolate!'
description:      'Welcome to my personal blog<br>Sharing life and tech.'
url:              https://github.com/ChengzhiSONG6/scz.github.io
baseurl:          /scz.github.io/
# url:              https://chengzhisong6.github.io


author:
  name:           'Chengzhi Song'
  email:          songchengzhiinhk@gmail.com

paginate:         5
paginate_path: "/blog/page:num/"

gems: [jekyll-paginate]

# custom vars
since:                  2020
# google_analytics:       UA-63207330-1
emailme:                mailto:czsong@surgery.cuhk.edu.hk
github:
  repo:                 https://chengzhisong6.github.io/song.github.io/

version:                Apr.23.2020
orcid_username:         0000-0002-0333-5776
googlescholar_username: S6_hs6wAAAAJ&hl
# researchgate_username: 
linkedin_username:      ChengzhiSong
github_username:        ChengzhiSong6
share_pdf:              no
share_video:            no
