# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Chengzhi Song
tagline:          'Chengzhi Song'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

# Custom vars
# version:          2.1.0
# github:
#   repo:           https://github.com/poole/hyde

author:
  name:           'Chengzhi Song'
  email:          songchengzhiinhk@gmail.com

paginate:         3
paginate_path: "blog/page:num"

gems: [jekyll-paginate]

# custom vars
since:                  2020
# google_analytics:       UA-63207330-1
emailme:                mailto:czsong@surgery.cuhk.edu.hk
github:
  repo:                 https://github.com/ChengzhiSong6/czsong.github.io/
version:                Mar.6.2020
# orcid_username:         0000-0003-4281-5120
# researcherid_username:  R-3094-2018
# googlescholar_username: fWi5tx8AAAAJ&hl
# researchgate_username:  Zerui_Wang
linkedin_username:      ChengzhiSong
github_username:        ChengzhiSong6
# share_pdf:              no
# share_video:            no
